name: bookservice
description: A new Flutter project.

version: 1.0.5+5

environment:
  sdk: ">=2.2.0 <3.0.0"
  # flutter: ">=1.5.9-pre.94 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # cloud_functions: ^0.0.4+1
  # firebase_database: ^1.0.4
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.0
  firebase_storage: ^3.0.0
  cloud_firestore: ^0.11.0+1
  firebase_messaging: ^5.0.1+1
  firebase_core: ^0.4.0

  flutter_localizations:
    sdk: flutter  
    
  intl: ^0.15.7

  uuid: ^2.0.1

  # dio: ^1.0.6
  
  fluro:  
    git: git@github.com:marscj/fluro.git 

  flutter_country_picker:
    git: git@github.com:marscj/flutter_country_picker.git
    
  # screen: ^0.0.4
  fluttertoast: ^3.0.4

  shared_preferences: ^0.5.2
  
  json_annotation: ^2.0.0

  image_picker: ^0.6.0+3

  card_settings: ^1.4.1

  cached_network_image: ^0.7.0

  # pull_to_refresh: ^1.1.5

  banner_view: ^1.1.2

  url_launcher: ^5.0.2

  # scoped_model: ^0.3.0

  google_places_picker: ^0.1.0

  flutter_map: ^0.5.0+1

  flutter_svg: ^0.12.4

dev_dependencies: 
  #flutter packages pub run build_runner build 
  build_runner: ^1.1.2
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png 
   - assets/2.0x/logo.png
   - assets/3.0x/logo.png

   - assets/slide1.jpg
   - assets/slide2.jpg
   - assets/slide3.jpg
   - assets/slide4.jpg
   - assets/slide5.jpg
   - assets/background.png
   - assets/title.png
   - assets/person.jpg
   - assets/company.jpg
   - assets/customer.jpg
   - assets/freelancer.jpg
   - assets/arabic.jpg
   - assets/english.jpg

   - assets/plumbing.svg
   - assets/ac.svg
   - assets/electrical.svg
   - assets/cleaning.svg
   
  fonts:
  - family:  MyFlutterApp
    fonts:
      - asset: font/MyFlutterApp.ttf